name: GitHub Streak Dashboard
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  streak-dashboard:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate Streak Dashboard
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: ${{ github.repository_owner }}
          template: classic
          base: ""
          config_timezone: Asia/Manila
          config_animations: yes
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: chartist
          plugin_habits_trim: yes
          plugin_calendar: yes
          plugin_calendar_limit: 0
          plugin_streaks: yes
          plugin_streaks_limit: 3
          config_padding: "10, 20, 10, 20"
          config_output: svg
          config_display: regular
          config_theme: dark
          config_base64: no
          config_twemoji: yes
          optimize: "css, xml, svg"
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: main
          committer_message: "🔥 Update GitHub streak dashboard"
          filename: github-streak-dashboard.svg
