name: Daily Coding Streak Metrics
on:
  # Schedule to run daily at midnight UTC to track streak
  schedule:
    - cron: "0 0 * * *"
  # Allow manual triggering for testing
  workflow_dispatch:
  # Run on push to main branch to update immediately
  push:
    branches: [ main, master ]

jobs:
  streak-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate Daily Coding Streak Metrics
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token (add this to your repository secrets)
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Basic configuration - minimal header only
          user: ${{ github.repository_owner }}
          template: classic
          base: ""
          config_timezone: Asia/Manila
          config_order: isocalendar
          config_animations: yes
          
          # ISO Calendar - Primary streak visualization (3D isometric style)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_isocalendar_3d: yes
          
          # Key sizing and styling adjustments
          config_padding: 6, 12, 6, 12
          config_output: svg
          config_display: regular
          
          # Match the exact dimensions from your reference image
          plugin_isocalendar_3d_size: 280
          plugin_isocalendar_3d_perspective: 1200
          plugin_isocalendar_3d_angle: 35
          
          # Optimize for clean output
          optimize: css, xml, svg
          config_base64: no
          config_twemoji: yes
          
          # Commit and push the generated metrics
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: main
          committer_message: "🔥 Update daily coding streak metrics"
          
          # Output configuration
          filename: streak-summary.svg
