name: Metrics
on:
  # Schedule to run daily at midnight UTC
  schedule:
    - cron: "0 0 * * *"
  # Allow manual triggering
  workflow_dispatch:
  # Run on push to main branch
  push:
    branches: [ main, master ]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token (add this to your repository secrets)
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Options
          user: ${{ github.repository_owner }}
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/New_York
          config_order: base.header, base.activity, base.community, base.repositories, base.metadata
          
          # Layout and sizing
          config_display: large
          config_animations: yes
          
          # Enable various plugins
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all
          
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          
          plugin_contributors: yes
          plugin_contributors_base: contributions
          plugin_contributors_head: master
          plugin_contributors_ignored: bot
          plugin_contributors_contributions: yes
          
          plugin_followup: yes
          plugin_followup_sections: repositories
          
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          
          plugin_code: yes
          plugin_code_lines: 12
          plugin_code_load: 400
          plugin_code_days: 3
          plugin_code_visibility: public
          
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_types: commit
          
          # Commit and push the generated metrics
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: main
          committer_message: "Update metrics"
          
          # Output file and sizing
          filename: metrics.svg
          config_display: large
          config_output: svg
          
          # Custom sizing options
          config_padding: 0, 8, 0, 8
          
          # Optimize for better performance
          optimize: css, xml, svg
