name: Daily Coding Streak Metrics
on:
  # Schedule to run daily at midnight UTC to track streak
  schedule:
    - cron: "0 0 * * *"
  # Allow manual triggering for testing
  workflow_dispatch:
  # Run on push to main branch to update immediately
  push:
    branches: [ main, master ]

jobs:
  streak-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate Daily Coding Streak Metrics
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token (add this to your repository secrets)
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Basic configuration - minimal header only
          user: ${{ github.repository_owner }}
          template: classic
          base: header
          config_timezone: America/New_York
          config_order: base.header, isocalendar
          config_animations: yes
          
          # ISO Calendar - Primary streak visualization (3D isometric style)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          # Commit and push the generated metrics
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: main
          committer_message: "🔥 Update daily coding streak metrics"
          
          # Output configuration - clean and minimal
          filename: streak-summary.svg
          config_padding: 4, 8, 4, 8
          
          # Clean minimal styling
          optimize: css, xml, svg
          config_display: regular
